#
# CMD
#
[cmd]
h:left
k:up
j:down
l:right

m:return

# prev/next tab
i:tab:ctrl,shift
o:tab:ctrl

#
# CONTROL
#
[ctrl]
# begin/end line
h:left:cmd
l:right:cmd

# prev/next word
j:left:opt
k:right:opt

#
# CAPSLOCK
#
[capslock]
h:left
k:up
j:down
l:right

m:return

# prev/next tab
i:tab:ctrl,shift
o:tab:ctrl
