[cmd]
h:left
k:up
j:down
l:right

m:return
d:delete
e:escape

# prev/next tab
i:tab:ctrl,shift
o:tab:ctrl

[ctrl]
# begin/end line
h:left:cmd
l:right:cmd

# prev/next word
j:left:opt
k:right:opt

[capslock]
h:left
k:up
j:down
l:right

m:return
d:delete
e:escape

# prev/next tab
i:tab:ctrl,shift
o:tab:ctrl
